services:
  db:
    image: postgres:16.1-alpine3.19
    environment:
      - "POSTGRES_USER=ttrpgcamp"
      - "POSTGRES_PASSWORD=ttrpgcamp"
    ports:
      - "5432:5432"
        
  ttrpgcamp.app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "CONNECTIONSTRINGS__MAIN=Host=db;Port=5432;User Id=ttrpgcamp;Password=ttrpgcamp"
