name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "dev" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "dev" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          dotnet-version: 8.0
      - name: Dotnet restore
        run: |
          dotnet restore --locked-mode src/TtrpgCamp.App.Client/TtrpgCamp.App.Client.csproj
          dotnet restore --locked-mode src/TtrpgCamp.App/TtrpgCamp.App.csproj
          dotnet restore --locked-mode test/TtrpgCamp.App.Client.Test/TtrpgCamp.App.Client.Test.csproj
          dotnet restore --locked-mode test/TtrpgCamp.App.Test/TtrpgCamp.App.Test.csproj
      - name: Dotnet build
        run: dotnet build -c Release --no-restore
      - name: Run Tests
        run: dotnet test -c Release --no-build
      - name: Dotnet Publish
        run: dotnet publish -c Release --no-build src/TtrpgCamp.App/TtrpgCamp.App.csproj -o bin/
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        run: docker build -t ${{ steps.meta.outputs.tags }} -f vm-copy.Dockerfile .  
      - name: Push Docker image
        run: docker push ${{ steps.meta.outputs.tags }}